version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: grocery-mart
      POSTGRES_USER: groceryMartUser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  backend:
    build:
      context: ./Backend/grocery-mart-backend
    container_name: spring-boot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/grocery-mart
      SPRING_DATASOURCE_USERNAME: groceryMartUser
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/grocery-mart-frontend
    container_name: react-frontend-app
    depends_on:
      - backend
    ports:
      - "3000:8080"
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
networks:
  app-network:
    driver: bridge      